# Supported funding model platforms

github: MiguelViannay

# Se você futuramente criar um link do Apoia.se, LivePix, ou quiser colocar
# um link direto para um site da OneViannay que tenha sua chave Pix,
# você pode remover o # da linha abaixo e colocar o link:
# custom: ['https://link-do-seu-pix-ou-apoia-se.com']
